// ═══════════════════════════════════════════
// Nexo CRM — Mock Data for Demo Mode
// Mirrors the Appwrite schema exactly
// ═══════════════════════════════════════════

// ─── Leads ──────────────────────────────
export const mockLeads = [
    {
        $id: "lead_001",
        name: "María García",
        email: "maria@techcorp.com",
        phone: "+593 99 123 4567",
        company: "TechCorp Solutions",
        source: "WhatsApp",
        stage: "new",
        score: 85,
        assignedTo: "demo_user_001",
        notes: "Interesada en plan Profesional",
        $createdAt: "2026-02-20T09:00:00.000Z",
        $updatedAt: "2026-02-28T14:30:00.000Z",
    },
    {
        $id: "lead_002",
        name: "Carlos López",
        email: "carlos@datapro.ec",
        phone: "+593 98 765 4321",
        company: "DataPro",
        source: "Referido",
        stage: "contacted",
        score: 70,
        assignedTo: "demo_user_001",
        notes: "Requiere demo personalizada",
        $createdAt: "2026-02-18T11:00:00.000Z",
        $updatedAt: "2026-02-27T10:00:00.000Z",
    },
    {
        $id: "lead_003",
        name: "Ana Martínez",
        email: "ana.m@gmail.com",
        phone: "+593 97 555 1234",
        company: "",
        source: "Sitio web",
        stage: "new",
        score: 60,
        assignedTo: "demo_user_001",
        notes: "",
        $createdAt: "2026-02-25T08:30:00.000Z",
        $updatedAt: "2026-02-25T08:30:00.000Z",
    },
    {
        $id: "lead_004",
        name: "Pedro Sánchez",
        email: "pedro@cloudinc.com",
        phone: "+593 96 111 2222",
        company: "CloudInc",
        source: "WhatsApp",
        stage: "contacted",
        score: 75,
        assignedTo: "demo_user_001",
        notes: "Seguimiento pendiente",
        $createdAt: "2026-02-15T14:00:00.000Z",
        $updatedAt: "2026-02-26T16:00:00.000Z",
    },
    {
        $id: "lead_005",
        name: "Laura Díaz",
        email: "laura.diaz@email.com",
        phone: "+593 95 333 4444",
        company: "",
        source: "Import",
        stage: "proposal",
        score: 55,
        assignedTo: "demo_user_001",
        notes: "Propuesta enviada el 02/25",
        $createdAt: "2026-02-10T10:00:00.000Z",
        $updatedAt: "2026-02-25T12:00:00.000Z",
    },
    {
        $id: "lead_006",
        name: "Roberto Ruiz",
        email: "roberto@softmax.io",
        phone: "+593 94 777 8888",
        company: "SoftMax",
        source: "Referido",
        stage: "negotiating",
        score: 90,
        assignedTo: "demo_user_001",
        notes: "Negociación avanzada, plan Enterprise",
        $createdAt: "2026-01-28T09:00:00.000Z",
        $updatedAt: "2026-02-28T18:00:00.000Z",
    },
    {
        $id: "lead_007",
        name: "Diana Flores",
        email: "diana@netgroup.com",
        phone: "+593 93 999 0000",
        company: "NetGroup",
        source: "WhatsApp",
        stage: "won",
        score: 95,
        assignedTo: "demo_user_001",
        notes: "¡Cerrado! Plan Profesional anual",
        $createdAt: "2026-01-20T07:00:00.000Z",
        $updatedAt: "2026-02-22T11:00:00.000Z",
    },
    {
        $id: "lead_008",
        name: "Fernando Morales",
        email: "fmorales@acme.com",
        phone: "+593 92 444 5555",
        company: "ACME Corp",
        source: "Sitio web",
        stage: "lost",
        score: 40,
        assignedTo: "demo_user_001",
        notes: "Eligió competencia por precio",
        $createdAt: "2026-02-01T13:00:00.000Z",
        $updatedAt: "2026-02-20T09:00:00.000Z",
    },
];

// ─── Contacts (converted leads) ─────────
export const mockContacts = [
    {
        $id: "contact_001",
        name: "Diana Flores",
        email: "diana@netgroup.com",
        phone: "+593 93 999 0000",
        company: "NetGroup",
        plan: "Profesional",
        convertedFrom: "lead_007",
        $createdAt: "2026-02-22T11:00:00.000Z",
    },
    {
        $id: "contact_002",
        name: "Sofía Ramos",
        email: "sofia@innovatech.ec",
        phone: "+593 91 222 3333",
        company: "InnovaTech",
        plan: "Enterprise",
        convertedFrom: "lead_ext_01",
        $createdAt: "2026-02-10T15:00:00.000Z",
    },
];

// ─── Partners MLM ───────────────────────
export const mockPartners = [
    {
        $id: "partner_001",
        name: "Jorge Ron",
        email: "jorge@upconnect.com",
        rank: "Diamante",
        leadsContacted: 45,
        closures: 12,
        recruits: 5,
        goalsCompleted: 8,
        goalsTotal: 10,
        status: "active",
        $createdAt: "2026-01-01T00:00:00.000Z",
    },
    {
        $id: "partner_002",
        name: "Lorena Vera",
        email: "lorena@upconnect.com",
        rank: "Oro",
        leadsContacted: 28,
        closures: 7,
        recruits: 3,
        goalsCompleted: 5,
        goalsTotal: 8,
        status: "active",
        $createdAt: "2026-01-15T00:00:00.000Z",
    },
    {
        $id: "partner_003",
        name: "Miguel Torres",
        email: "miguel@partner.com",
        rank: "Plata",
        leadsContacted: 15,
        closures: 3,
        recruits: 1,
        goalsCompleted: 2,
        goalsTotal: 6,
        status: "active",
        $createdAt: "2026-02-01T00:00:00.000Z",
    },
];

// ─── Tasks ──────────────────────────────
export const mockTasks = [
    {
        $id: "task_001",
        title: "Llamar a María García",
        description: "Seguimiento de propuesta enviada",
        priority: "high",
        status: "pending",
        dueDate: "2026-03-03T10:00:00.000Z",
        assignedTo: "demo_user_001",
        relatedTo: "lead_001",
        $createdAt: "2026-02-28T09:00:00.000Z",
    },
    {
        $id: "task_002",
        title: "Preparar demo para DataPro",
        description: "Demo personalizada del módulo de postventa",
        priority: "medium",
        status: "in_progress",
        dueDate: "2026-03-04T14:00:00.000Z",
        assignedTo: "demo_user_001",
        relatedTo: "lead_002",
        $createdAt: "2026-02-27T11:00:00.000Z",
    },
    {
        $id: "task_003",
        title: "Enviar contrato a Roberto",
        description: "Contrato plan Enterprise anual",
        priority: "urgent",
        status: "pending",
        dueDate: "2026-03-02T18:00:00.000Z",
        assignedTo: "demo_user_001",
        relatedTo: "lead_006",
        $createdAt: "2026-02-28T16:00:00.000Z",
    },
    {
        $id: "task_004",
        title: "Onboarding Diana Flores",
        description: "Configuración inicial del CRM para NetGroup",
        priority: "medium",
        status: "done",
        dueDate: "2026-02-25T09:00:00.000Z",
        assignedTo: "demo_user_001",
        relatedTo: "contact_001",
        $createdAt: "2026-02-22T12:00:00.000Z",
    },
];

// ─── Activity Log ───────────────────────
export const mockActivityLog = [
    {
        $id: "log_001",
        action: "lead_created",
        description: "Nuevo lead: María García (TechCorp)",
        userId: "demo_user_001",
        $createdAt: "2026-02-28T14:30:00.000Z",
    },
    {
        $id: "log_002",
        action: "lead_moved",
        description: "Roberto Ruiz movido a Negociando",
        userId: "demo_user_001",
        $createdAt: "2026-02-28T12:00:00.000Z",
    },
    {
        $id: "log_003",
        action: "lead_won",
        description: "¡Cierre! Diana Flores — Plan Profesional",
        userId: "demo_user_001",
        $createdAt: "2026-02-22T11:00:00.000Z",
    },
    {
        $id: "log_004",
        action: "task_completed",
        description: "Onboarding Diana Flores completado",
        userId: "demo_user_001",
        $createdAt: "2026-02-25T17:00:00.000Z",
    },
    {
        $id: "log_005",
        action: "partner_joined",
        description: "Nuevo socio: Miguel Torres (rango Plata)",
        userId: "demo_user_001",
        $createdAt: "2026-02-01T09:00:00.000Z",
    },
];

// ─── Calendar Events ────────────────────
export const mockCalendarEvents = [
    {
        $id: "event_001",
        title: "Demo con DataPro",
        date: "2026-03-04T14:00:00.000Z",
        description: "Presentación módulo postventa",
        userId: "demo_user_001",
    },
    {
        $id: "event_002",
        title: "Firma contrato SoftMax",
        date: "2026-03-05T10:00:00.000Z",
        description: "Roberto Ruiz — Enterprise",
        userId: "demo_user_001",
    },
    {
        $id: "event_003",
        title: "Reunión equipo semanal",
        date: "2026-03-03T09:00:00.000Z",
        description: "Review KPIs y pipeline",
        userId: "demo_user_001",
    },
];

// ─── KPI Summary (pre-calculated) ──────
export const mockKpis = {
    totalLeads: mockLeads.length,
    totalContacts: mockContacts.length,
    totalClosures: mockLeads.filter((l) => l.stage === "won").length,
    pipelineValue: 24500,
    leadsByStage: {
        new: mockLeads.filter((l) => l.stage === "new").length,
        contacted: mockLeads.filter((l) => l.stage === "contacted").length,
        proposal: mockLeads.filter((l) => l.stage === "proposal").length,
        negotiating: mockLeads.filter((l) => l.stage === "negotiating").length,
        won: mockLeads.filter((l) => l.stage === "won").length,
        lost: mockLeads.filter((l) => l.stage === "lost").length,
    },
    partnersActive: mockPartners.filter((p) => p.status === "active").length,
    tasksOverdue: mockTasks.filter((t) => t.status === "pending" && new Date(t.dueDate) < new Date()).length,
};
